spring:
  application:
    name: client-service

server:
  # you can pass argument to JVM (java -Dport="8082" -jar <jar-name>)
  port: ${port:8081}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    # for testing for instance
    registry-fetch-interval-seconds: 5
    disable-delta: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

application:
  region: ${region:Unknown}

